export default {
    status: 'OK',
    copyright: 'Copyright (c) 2021 The New York Times Company. All Rights Reserved.',
    section: 'Arts',
    last_updated: '2021-12-05T22:19:35-05:00',
    num_results: 34,
    results: [
        {
            section: 'arts',
            subsection: 'television',
            title: 'Best TV Shows of 2021',
            abstract:
                'From Bo Burnham to “We Are Lady Parts,” the best in television this year offered ingenuity, humor, defiance and hope.',
            url: 'https://www.nytimes.com/2021/12/03/arts/television/best-tv-shows.html',
            uri: 'nyt://article/a55dfe85-766a-5d6f-a800-6806d675bc27',
            byline: 'By James Poniewozik, Mike Hale and Margaret Lyons',
            item_type: 'Article',
            updated_date: '2021-12-05T08:08:14-05:00',
            created_date: '2021-12-03T08:55:21-05:00',
            published_date: '2021-12-03T08:55:21-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Two Thousand Twenty One',
                'Television',
                'Betty (TV Program)',
                'Brooklyn Nine-Nine (TV Program)',
                'CB Strike: Lethal White (TV Program)',
                'Dickinson (TV Program)',
                'Forbrydelsen (TV Program)',
                'Gomorrah (TV Program)',
                'Hacks (TV Program)',
                'In My Skin (TV Program)',
                'Infinity Train (TV Program)',
                "It's a Sin (TV Program)",
                "Kim's Convenience (TV Program)",
                'Laetitia (TV Program)',
                'Mom (TV Program)',
                'Mr Inbetween (TV Program)',
                'Philly DA (TV Program)',
                'Pose (TV Program)',
                'Reservation Dogs (TV Program)',
                'Succession (TV Program)',
                'The White Lotus (TV Program)',
                'Younger (TV Program)',
                'The Underground Railroad (Book)',
                'Station Eleven (TV Program)',
            ],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/arts/03best-tv-shows-2021/03best-tv-shows-2021-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        '“The White Lotus,” Pose” and “Laetitia” (with from left, Murray Bartlett, Mj Rodriguez and Marie Colomb) were among television’s best in 2021.',
                    copyright: 'From left: Mario Perez/HBO; Eric Liebowitz/FX; Jerome Prebois/HBO ',
                },
            ],
            short_url: 'https://nyti.ms/32MHxRy',
        },
        {
            section: 'arts',
            subsection: 'design',
            title: 'Signs of Sea Change at Art Basel Miami: More Galleries of Color',
            abstract:
                'Changes to eligibility requirements enabled more diversity at the fair, which roared back for the first time since the pandemic.',
            url: 'https://www.nytimes.com/2021/12/04/arts/design/art-basel-miami-diversity.html',
            uri: 'nyt://article/65f04b70-2a3d-59be-9dff-1298bae5c11b',
            byline: 'By Robin Pogrebin',
            item_type: 'Article',
            updated_date: '2021-12-05T23:52:32-05:00',
            created_date: '2021-12-04T17:29:10-05:00',
            published_date: '2021-12-04T17:29:10-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Art Basel Miami Beach',
                'Art',
                'Conventions, Fairs and Trade Shows',
                'Black People',
                'Minorities',
            ],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/multimedia/05art-basel-Afriart-01/05art-basel-Afriart-01-superJumbo-v2.jpg',
                    format: 'superJumbo',
                    height: 1333,
                    width: 2000,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'The Tanzanian artist Sungi Mlengeya, right, at the Afriart Gallery space at Art Basel Miami Beach with her portrait paintings of women.',
                    copyright: 'Alfonso Duran for The New York Times',
                },
            ],
            short_url: 'https://nyti.ms/3dlener',
        },
        {
            section: 'arts',
            subsection: 'design',
            title: 'Cambodia Says Looter Helping It Reclaim Stolen Artifacts Has Died',
            abstract:
                'Officials said they plan to continue to use evidence gathered from the reformed looter to pursue the return of many artifacts from museums and private collections.',
            url: 'https://www.nytimes.com/2021/12/05/arts/design/cambodian-effort-to-find-artifacts-wont-end-with-informants-death.html',
            uri: 'nyt://article/8a4dbe31-8267-50df-800a-75b50646ef41',
            byline: 'By Tom Mashberg',
            item_type: 'Article',
            updated_date: '2021-12-05T21:25:53-05:00',
            created_date: '2021-12-05T16:00:01-05:00',
            published_date: '2021-12-05T16:00:01-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Arts and Antiquities Looting',
                'Museums',
                'Art',
                'Collectors and Collections',
            ],
            org_facet: ['Metropolitan Museum of Art', 'Khmer Rouge'],
            per_facet: ['Toek Tik'],
            geo_facet: ['Cambodia'],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/06/arts/06lion-alt/merlin_198821499_a30773f7-9f1f-4784-8497-e7981161a81b-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Toek Tik at Prasat Thom Temple in Koh Ker, Cambodia, looking for part of an artifact from his plundering days. ',
                    copyright: 'Thomas Cristofoletti',
                },
            ],
            short_url: 'https://nyti.ms/3xU50ff',
        },
        {
            section: 'theater',
            subsection: '',
            title: '‘Mrs. Doubtfire’ Review: Nanny Doesn’t Know Best',
            abstract:
                'The new family-friendly musical, adapted from the hit movie, ends up cowering in the original film’s shadow.',
            url: 'https://www.nytimes.com/2021/12/05/theater/mrs-doubtfire-review-broadway.html',
            uri: 'nyt://article/b58ab3a9-2841-5f27-a244-d76b56266c8d',
            byline: 'By Maya Phillips',
            item_type: 'Article',
            updated_date: '2021-12-05T22:00:07-05:00',
            created_date: '2021-12-05T22:00:07-05:00',
            published_date: '2021-12-05T22:00:07-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Theater',
                'Music',
                'Movies',
                'Mrs Doubtfire (Play)',
                'Homosexuality and Bisexuality',
                'Transgender and Transsexuals',
            ],
            org_facet: [],
            per_facet: [
                'McClure, Rob',
                'Kirkpatrick, Karey (1964- )',
                'Kirkpatrick, Wayne (1961- )',
                'Ghee, J Harrison',
                'Zaks, Jerry',
                'Oscar, Brad (1964- )',
                "O'Farrell, John (1962- )",
                'Korins, David',
            ],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/arts/05DOUBTFIRE-1/05DOUBTFIRE-1-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1202,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Rob McClure, center, as Mrs. Doubtfire in the new musical at the Stephen Sondheim Theater.',
                    copyright: 'Sara Krulwich/The New York Times',
                },
            ],
            short_url: 'https://nyti.ms/3poIdUW',
        },
        {
            section: 'theater',
            subsection: '',
            title: 'Best Theater of 2021',
            abstract:
                'Digital innovation continued this year, but experiencing plays in isolation grew tiring. Then came an in-person season as exciting as a child’s first fireworks.',
            url: 'https://www.nytimes.com/2021/12/03/theater/best-theater.html',
            uri: 'nyt://article/d4a03ddc-bed3-5df1-b2bf-ef420b1bb3c2',
            byline: 'By Jesse Green, Maya Phillips, Laura Collins-Hughes, Scott Heller, Alexis Soloski and Elisabeth Vincentelli',
            item_type: 'Article',
            updated_date: '2021-12-03T12:07:09-05:00',
            created_date: '2021-12-03T10:20:34-05:00',
            published_date: '2021-12-03T10:20:34-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Theater',
                'Caroline, or Change (Play)',
                "Clyde's (Play)",
                'Dana H. (Play)',
                'Is This a Room: Reality Winner Verbatim Transcription (Play)',
                'Merry Wives (Play)',
                'Pass Over (Play)',
                'Six (Play)',
                'Sanctuary City (Play)',
                'Trouble in Mind  (Play)',
                'What Happened?: The Michaels Abroad (Play)',
                'A Thousand Ways (Part Two): An Encounter (Play)',
                'Romeo and Juliet (Play)',
                'The Poltergeist (Play)',
                'Hamlet (Play)',
                'Spring Awakening (Play)',
                'The Lehman Trilogy (Play)',
                'Gorbachev (Play)',
                'Only an Octave Apart (Play)',
                'Cinderella (Play)',
                'A Dozen Dreams (Play)',
                'What to Send Up When It Goes Down (Play)',
                'The Merry Wives of Windsor (Play)',
                'Blindness (Play)',
            ],
            org_facet: [],
            per_facet: [
                "O'Connell, Deirdre (Actor)",
                'Potter, Joseph (Actor)',
                'McKellen, Ian',
                'Danes, Claire',
                'Dancy, Hugh',
            ],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/arts/03best-theater-2021/03best-theater-2021-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'From left, Sharon D Clarke in “Caroline, or Change,” Adrianna Hicks in “Six” and Deirdre O’Connell in “Dana H.” Their shows are among the year’s best.',
                    copyright: 'Photographs by Sara Krulwich/The New York Times',
                },
            ],
            short_url: 'https://nyti.ms/3omPKo5',
        },
        {
            section: 'arts',
            subsection: 'television',
            title: 'Review: ‘Landscapers’ Is Not Your Typical True-Crime Love Story',
            abstract:
                'Olivia Colman and David Thewlis star in this HBO tale of devotion, murdered parents and very expensive autographs.',
            url: 'https://www.nytimes.com/2021/12/05/arts/television/landscapers-review.html',
            uri: 'nyt://article/dfd0bf28-5f5f-5a57-9b28-3f73f8842c8d',
            byline: 'By Mike Hale',
            item_type: 'Article',
            updated_date: '2021-12-05T21:25:37-05:00',
            created_date: '2021-12-05T15:18:30-05:00',
            published_date: '2021-12-05T15:18:30-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Television',
                'Murders, Attempted Murders and Homicides',
                'Landscapers  (TV Program)',
            ],
            org_facet: ['Home Box Office'],
            per_facet: [
                'Sharpe, Will (1986- )',
                'Thewlis, David',
                'Colman, Olivia',
                'Susan Edwards',
                'Christopher Edwards',
            ],
            geo_facet: ['England'],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/arts/05landscapers-review/merlin_198728562_92a74c21-1614-4e01-916d-ac2ab013d3bf-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1272,
                    width: 1920,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        ' David Thewlis plays Christopher Edwards in “Landscapers,” a new true-crime mini-series on HBO.',
                    copyright: 'Stefania Rosini/HBO',
                },
            ],
            short_url: 'https://nyti.ms/3Dso99h',
        },
        {
            section: 'arts',
            subsection: 'television',
            title: '‘And Just Like That’: The Shoe Must Go On',
            abstract:
                'In the ’90s, “Sex and the City” celebrated single women. Can a new, more nuanced version make a comedy of middle-aged ones?',
            url: 'https://www.nytimes.com/2021/12/03/arts/television/and-just-like-that-sex-and-the-city.html',
            uri: 'nyt://article/2668c6f2-b60e-561b-a383-4bffaf7844b8',
            byline: 'By Alexis Soloski',
            item_type: 'Article',
            updated_date: '2021-12-05T14:45:48-05:00',
            created_date: '2021-12-03T05:00:14-05:00',
            published_date: '2021-12-03T05:00:14-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Television',
                'Sex and the City (TV Program)',
                'And Just Like That ... (TV Program)',
            ],
            org_facet: ['HBO Max'],
            per_facet: [
                'Parker, Sarah Jessica',
                'Nixon, Cynthia',
                'Davis, Kristin',
                'King, Michael Patrick',
                'Parker, Nicole Ari',
                'Choudhury, Sarita',
                'Ramirez, Sara (1975- )',
                'Pittman, Karen',
            ],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/arts/05SATC/05SATC-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        '“And Just Like That” revisits three of the four main characters from “Sex and the City,” now in their 50s (with, from left, Cynthia Nixon, Sarah Jessica Parker and Kristin Davis).',
                    copyright: 'Craig Blankenhorn/HBO',
                },
            ],
            short_url: 'https://nyti.ms/3IiTejm',
        },
        {
            section: 'movies',
            subsection: '',
            title: 'How ‘West Side Story’ Could Make (Even More) Oscar History',
            abstract:
                'After premiering this week, the remake has vaulted into contention, with nominations possible for the film, director Steven Spielberg, Rita Moreno and others.',
            url: 'https://www.nytimes.com/2021/12/03/movies/west-side-story-oscar.html',
            uri: 'nyt://article/bd1ea342-d633-5152-8b25-5a97af152b64',
            byline: 'By Kyle Buchanan',
            item_type: 'Article',
            updated_date: '2021-12-03T12:25:21-05:00',
            created_date: '2021-12-03T12:25:21-05:00',
            published_date: '2021-12-03T12:25:21-05:00',
            material_type_facet: '',
            kicker: 'The Projectionist',
            des_facet: ['Movies', 'Academy Awards (Oscars)', 'West Side Story (2021) (Movie)'],
            org_facet: [],
            per_facet: [
                'DeBose, Ariana',
                'Faist, Mike',
                'Moreno, Rita',
                'Peck, Justin',
                'Kaminski, Janusz',
                'Kushner, Tony',
                'Spielberg, Steven',
            ],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/arts/03projectionist-wss1/merlin_198687915_17e673ab-ab07-4d7a-969d-ca6e03b6f394-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1401,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption: 'Rachel Zegler in a scene from the new “West Side Story.”',
                    copyright: 'Niko Tavernise/20th Century Studios\n',
                },
            ],
            short_url: 'https://nyti.ms/31uLoCk',
        },
        {
            section: 'movies',
            subsection: '',
            title: 'Netflix Holiday Movies Ranked, From Tree Toppers to Lumps of Coal',
            abstract:
                'Is the streaming service delivering goodies in its holiday stockings? We make an assessment.',
            url: 'https://www.nytimes.com/2021/12/03/movies/netflix-holiday-christmas.html',
            uri: 'nyt://article/5bcbd99d-0acf-532f-abea-35049c6fc9a4',
            byline: 'By Elisabeth Vincentelli',
            item_type: 'Article',
            updated_date: '2021-12-03T17:14:55-05:00',
            created_date: '2021-12-03T12:27:45-05:00',
            published_date: '2021-12-03T12:27:45-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Movies',
                'Christmas',
                'A Boy Called Christmas (Movie)',
                'A Castle for Christmas (Movie)',
                'Love Hard (Movie)',
                'Single All the Way (Movie)',
                'The Princess Switch 3: Romancing the Star (Movie)',
                'The Claus Family (Movie)',
                'Father Christmas Is Back (Movie)',
            ],
            org_facet: ['Netflix Inc'],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/04/arts/netflixholiday1/merlin_198348621_b21c7f2a-5f1a-4a70-a48a-964b5ed1ecd5-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'From left, Philemon Chambers, Jennifer Coolidge and Michael Urie in “Single All the Way.”',
                    copyright: 'Philippe Bosse/Netflix',
                },
            ],
            short_url: 'https://nyti.ms/3xPipFo',
        },
        {
            section: 'movies',
            subsection: '',
            title: 'Best Movies of 2021',
            abstract:
                'Even when a film wasn’t great, filmgoing was. But there were some truly wonderful releases, ranging from music docs and musicals to westerns and the just plain weird.',
            url: 'https://www.nytimes.com/2021/12/06/movies/best-movies.html',
            uri: 'nyt://article/4a8ba125-8433-512a-9863-6df4a6a9ce20',
            byline: 'By A.O. Scott and Manohla Dargis',
            item_type: 'Article',
            updated_date: '2021-12-06T05:00:24-05:00',
            created_date: '2021-12-06T05:00:24-05:00',
            published_date: '2021-12-06T05:00:24-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Movies',
                'Summer of Soul (... Or, When the Revolution Could Not Be Televised) (Movie)',
                'Bad Luck Banging or Loony Porn (Movie)',
                'The Power of the Dog (Movie)',
                'Petite Maman (Movie)',
                'Bring Your Own Brigade (Movie)',
                'Bergman Island (Movie)',
                'Drive My Car (Movie)',
                'Memoria (Movie)',
                'West Side Story (2021) (Movie)',
                'The Velvet Underground (Movie)',
                'Passing (Movie)',
                'Azor (Movie)',
                'The Card Counter (Movie)',
                'The Disciple (Movie)',
                'Wheel of Fortune and Fantasy (Movie)',
                'Spencer (Movie)',
                'Two Thousand Twenty One',
            ],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/06/arts/06best-movies-2021/06best-movies-2021-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Benedict Cumberbatch in “The Power of the Dog,” left, Kristen Stewart in “Spencer” and Ariana DeBose in “West Side Story.”',
                    copyright:
                        'From left: Kirsty Griffin/Netflix; Pablo Larrain/Neon; Niko Tavernise/20th Century Studios',
                },
            ],
            short_url: 'https://nyti.ms/3ExUUTJ',
        },
        {
            section: 'arts',
            subsection: 'television',
            title: 'What’s on TV This Week: ‘Landscapers’ and ‘Live in Front of a Studio Audience’',
            abstract:
                'David Thewlis and Olivia Colman star in a true-crime mini-series on HBO. And an ABC special brings back the 1980s sitcoms “The Facts of Life” and “Diff’rent Strokes.”',
            url: 'https://www.nytimes.com/2021/12/06/arts/television/whats-on-tv-this-week-landscapers-live-in-front-of-a-studio-audience.html',
            uri: 'nyt://article/af1d5e15-675d-5aec-9c03-add91a0241fd',
            byline: 'By Gabe Cohn',
            item_type: 'Article',
            updated_date: '2021-12-06T01:00:05-05:00',
            created_date: '2021-12-06T01:00:05-05:00',
            published_date: '2021-12-06T01:00:05-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Television', 'Movies'],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/06/multimedia/06tvcol-landscapers-sub/06tvcol-landscapers-sub-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1275,
                    width: 1912,
                    type: 'image',
                    subtype: 'photo',
                    caption: 'Olivia Colman in “Landscapers.”',
                    copyright: 'Stefania Rosini/HBO',
                },
            ],
            short_url: 'https://nyti.ms/3dkaN4i',
        },
        {
            section: 'arts',
            subsection: 'television',
            title: '‘Insecure’ Recap, Season 5, Episode 7: Questions, Questions',
            abstract:
                'For Issa and the girls, a day of relaxation turns into a night of introspection.',
            url: 'https://www.nytimes.com/2021/12/05/arts/television/insecure-recap.html',
            uri: 'nyt://article/b3c2cd13-2264-5b55-ba5b-e161c946f59a',
            byline: 'By Sandra E. Garcia',
            item_type: 'Article',
            updated_date: '2021-12-05T22:31:02-05:00',
            created_date: '2021-12-05T22:31:02-05:00',
            published_date: '2021-12-05T22:31:02-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Television', 'Insecure (TV Program)'],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/arts/05insecure/05insecure-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 672,
                    width: 1006,
                    type: 'image',
                    subtype: 'photo',
                    caption: 'Issa Rae in “Insecure.”',
                    copyright: 'HBO',
                },
            ],
            short_url: 'https://nyti.ms/3orlDfe',
        },
        {
            section: 'arts',
            subsection: 'television',
            title: '‘Succession’ Season 3, Episode 8: Italian Ice',
            abstract:
                'Kendall didn’t come out of the last family wedding so well. His mother’s Tuscan nuptials don’t look any more promising.',
            url: 'https://www.nytimes.com/2021/12/05/arts/television/succession-recap-episode-8.html',
            uri: 'nyt://article/415cd25f-23f8-52df-ae94-63a6bd2fa0bf',
            byline: 'By Noel Murray',
            item_type: 'Article',
            updated_date: '2021-12-05T22:05:04-05:00',
            created_date: '2021-12-05T22:05:04-05:00',
            published_date: '2021-12-05T22:05:04-05:00',
            material_type_facet: '',
            kicker: 'Succession',
            des_facet: ['Television', 'Succession (TV Program)'],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/arts/05succession-recap/05succession-recap-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1290,
                    width: 1920,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Kendall hits a wall. As usual, it’s his family. From left, Jeremy Strong, Kieran Culkin and Brian Cox in a scene from “Succession.”',
                    copyright: 'Graeme Hunter/HBO',
                },
            ],
            short_url: 'https://nyti.ms/3Ggt1jt',
        },
        {
            section: 'arts',
            subsection: 'dance',
            title: 'Exploring the Dimensions of Black Power at Alvin Ailey',
            abstract:
                'Alvin Ailey American Dance Theater returns to New York City Center with stage premieres by Robert Battle and Jamar Roberts and a stunning “Lazarus.”',
            url: 'https://www.nytimes.com/2021/12/05/arts/dance/alvin-ailey-city-center-black-power.html',
            uri: 'nyt://article/8dbcf82b-5e11-5a00-b396-a1b6a7c2f5bd',
            byline: 'By Gia Kourlas',
            item_type: 'Article',
            updated_date: '2021-12-05T21:20:28-05:00',
            created_date: '2021-12-05T15:03:06-05:00',
            published_date: '2021-12-05T15:03:06-05:00',
            material_type_facet: '',
            kicker: 'Critic’s Notebook',
            des_facet: [
                'Dancing',
                'Coronavirus (2019-nCoV)',
                'Black People',
                'For Four (Dance)',
                'Holding Space (Dance)',
                'Lazarus (Dance)',
                'Revelations (Dance)',
            ],
            org_facet: ['Ailey, Alvin, American Dance Theater', 'New York City Center Theater'],
            per_facet: ['Battle, Robert', 'Gilmer, James', 'Roberts, Jamar', 'Harris, Rennie'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/arts/Ailey-review/Ailey-review---superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Renaldo Maurice in Rennie Harris’s “Lazarus,” from 2018, which had a renewed power and urgency on Thursday.',
                    copyright: 'Nan Melville',
                },
            ],
            short_url: 'https://nyti.ms/3Intsuo',
        },
        {
            section: 'theater',
            subsection: '',
            title: 'Antony Sher, Actor Acclaimed for His Versatility, Dies at 72',
            abstract:
                'In his long career, most of it with the Royal Shakespeare Company, he played everyone from King Lear to Primo Levi to Ringo Starr.',
            url: 'https://www.nytimes.com/2021/12/05/theater/antony-sher-dead.html',
            uri: 'nyt://article/3c1b73d9-0042-5c84-be86-76a135bc646c',
            byline: 'By Roslyn Sulcas',
            item_type: 'Article',
            updated_date: '2021-12-05T22:53:52-05:00',
            created_date: '2021-12-05T14:46:47-05:00',
            published_date: '2021-12-05T14:46:47-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Deaths (Obituaries)', 'Theater', 'Actors and Actresses'],
            org_facet: ['Royal Shakespeare Co'],
            per_facet: ['Sher, Antony', 'Shakespeare, William'],
            geo_facet: ['England', 'South Africa'],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/06/obituaries/04sher-1/04sher-1-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1897,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Antony Sher in the title role of “King Lear” in 2018. He was closely associated with the Royal Shakespeare Company for more than four decades.',
                    copyright: 'Richard Termine/BAM',
                },
            ],
            short_url: 'https://nyti.ms/3xV29Tl',
        },
        {
            section: 'books',
            subsection: '',
            title: '‘The Fortune Men,’ a Novel That Remembers a Man Wrongly Sentenced to Death',
            abstract:
                'Nadifa Mohamed’s third novel, shortlisted for this year’s Booker Prize, is about Mahmood Mattan, a young Somali sailor who was falsely accused of a violent murder.',
            url: 'https://www.nytimes.com/2021/12/05/books/review-fortune-men-nadifa-mohamed.html',
            uri: 'nyt://article/c2bab67d-addf-5708-9e4b-fcb61504b5af',
            byline: 'By Dwight Garner',
            item_type: 'Article',
            updated_date: '2021-12-05T21:21:41-05:00',
            created_date: '2021-12-05T14:35:56-05:00',
            published_date: '2021-12-05T14:35:56-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['The Fortune Men (Book)', 'Books and Literature'],
            org_facet: [],
            per_facet: ['Mohamed, Nadifa'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/books/05BOOKMOHAMED1/05BOOKMOHAMED1-superJumbo.png',
                    format: 'superJumbo',
                    height: 2048,
                    width: 1484,
                    type: 'image',
                    subtype: 'photo',
                    caption: '',
                    copyright: '',
                },
            ],
            short_url: 'https://nyti.ms/3EqQGxd',
        },
        {
            section: 'arts',
            subsection: 'music',
            title: 'Review: An Ambitious Project Returns at the Philharmonic',
            abstract:
                'Project 19, the orchestra’s series commissioning female composers, came back with a new work by Joan Tower.',
            url: 'https://www.nytimes.com/2021/12/05/arts/music/new-york-philharmonic.html',
            uri: 'nyt://article/40cbfd79-8ffa-5b25-8bad-3d9259045622',
            byline: 'By Anthony Tommasini',
            item_type: 'Article',
            updated_date: '2021-12-05T21:31:52-05:00',
            created_date: '2021-12-05T11:26:30-05:00',
            published_date: '2021-12-05T11:26:30-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Classical Music'],
            org_facet: ['New York Philharmonic'],
            per_facet: ['Ax, Emanuel', 'Tower, Joan', 'van Zweden, Jaap'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/arts/05nyphil-online/merlin_198803400_0928341c-a11b-4430-a76d-a6eae304962c-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'From left: Joan Tower takes a bow after the premiere of her “1920/2019” with the New York Philharmonic, joined by the violinists Sheryl Staples and Michelle Kim and Jaap van Zweden, the orchestra’s music director.',
                    copyright: 'Chris Lee',
                },
            ],
            short_url: 'https://nyti.ms/3Dq6tuM',
        },
        {
            section: 'arts',
            subsection: 'television',
            title: 'Eddie Mekka, a Star of ‘Laverne & Shirley,’ Is Dead at 69',
            abstract:
                'As Carmine Ragusa on the hit sitcom, he got to show off his singing, tap-dancing and gymnastic skills — and to croon “Rags to Riches” many times.',
            url: 'https://www.nytimes.com/2021/12/05/arts/television/eddie-mekka-dead.html',
            uri: 'nyt://article/0233e1bd-473e-5d44-b9b7-b3042bb57ce8',
            byline: 'By Anita Gates',
            item_type: 'Article',
            updated_date: '2021-12-05T22:56:36-05:00',
            created_date: '2021-12-05T10:13:03-05:00',
            published_date: '2021-12-05T10:13:03-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Deaths (Obituaries)',
                'Laverne & Shirley (TV Program)',
                'Actors and Actresses',
                'Television',
                'Theater',
            ],
            org_facet: [],
            per_facet: ['Mekka, Eddie (1952-2021)'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/06/obituaries/06Mekka-obit1/03Mekka-1-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1367,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Eddie Mekka with Cindy Williams, left, and Penny Marshall in an episode of “Laverne & Shirley.”',
                    copyright:
                        'ABC Photo Archives/Disney General Entertainment Content via Getty Images',
                },
            ],
            short_url: 'https://nyti.ms/3pLMAtB',
        },
        {
            section: 'arts',
            subsection: '',
            title: 'Lawrence Weiner, Artist Whose Medium Was Language, Dies at 79',
            abstract:
                'A pioneer of the Conceptual art movement, he used words as his métier more than any other artist of his generation.',
            url: 'https://www.nytimes.com/2021/12/04/arts/lawrence-weiner-dead.html',
            uri: 'nyt://article/2583627e-ea34-59be-a089-b59d4449f8b1',
            byline: 'By Randy Kennedy',
            item_type: 'Article',
            updated_date: '2021-12-04T20:48:32-05:00',
            created_date: '2021-12-04T19:55:17-05:00',
            published_date: '2021-12-04T19:55:17-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Deaths (Obituaries)', 'Art', 'Sculpture', 'Language and Languages'],
            org_facet: [
                'Goodman, Marian, Gallery (Manhattan, NY)',
                'Whitney Museum of American Art',
            ],
            per_facet: ['Weiner, Lawrence'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/obituaries/03weiner-1/merlin_147290979_f3d822e4-c3f7-4bee-afc3-19c6181224e6-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1463,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'The conceptual artist Lawrence Weiner at his studio in Manhattan in 2018. He described his work as “language + the materials referred to.”',
                    copyright: 'An Rong Xu for The New York Times',
                },
            ],
            short_url: 'https://nyti.ms/31vQfD8',
        },
        {
            section: 'books',
            subsection: '',
            title: 'A Thriller in Vermont and a Camera Floating in the Ocean',
            abstract: 'Our critic recommends old and new books.',
            url: 'https://www.nytimes.com/2021/12/04/books/read-like-the-wind.html',
            uri: 'nyt://article/f392e484-46be-5e88-b6e0-1b72e6de8869',
            byline: 'By Molly Young',
            item_type: 'Article',
            updated_date: '2021-12-04T08:00:03-05:00',
            created_date: '2021-12-04T08:00:03-05:00',
            published_date: '2021-12-04T08:00:03-05:00',
            material_type_facet: '',
            kicker: 'read like the wind',
            des_facet: ['Books and Literature'],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/11/20/books/20RLTW-VELAZQUEZ/20RLTW-VELAZQUEZ-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 850,
                    width: 709,
                    type: 'image',
                    subtype: 'photo',
                    caption: '',
                    copyright: '"Santa Rufina" by Diego Velázquez',
                },
            ],
            short_url: 'https://nyti.ms/3xTTssb',
        },
        {
            section: 'arts',
            subsection: 'music',
            title: 'Franz Streitwieser, Trumpet Maestro With a Trove of Brass, Dies at 82',
            abstract:
                'He accumulated more than 1,000 items with provenances spanning centuries, all housed for a time in a converted barn in rural Pennsylvania.',
            url: 'https://www.nytimes.com/2021/12/03/arts/music/franz-streitwieser-dead.html',
            uri: 'nyt://article/4a368029-99aa-5ed9-bb4a-9f6e5d618e2f',
            byline: 'By Annabelle Williams',
            item_type: 'Article',
            updated_date: '2021-12-04T15:46:26-05:00',
            created_date: '2021-12-03T16:47:08-05:00',
            published_date: '2021-12-03T16:47:08-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Trumpets',
                'Music',
                'Musical Instruments',
                'Deaths (Obituaries)',
                'Collectors and Collections',
                'Museums',
            ],
            org_facet: [],
            per_facet: ['Streitwieser, Franz (1939-2021)'],
            geo_facet: ['Austria'],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/04/obituaries/04Streitwieser-obit/merlin_198328671_6bf84c4a-8a19-4553-9404-f1da77f955f3-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1426,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Franz Streitwieser, a professional trumpeter, began collecting brass instruments as a young man and amassed an enormous collection that he housed in a Pennsylvania barn.',
                    copyright: 'via Steitwieser family',
                },
            ],
            short_url: 'https://nyti.ms/3pokww6',
        },
        {
            section: 'at-home',
            subsection: '',
            title: 'What to Do This Weekend',
            abstract: 'It’s best-of season.',
            url: 'https://www.nytimes.com/2021/12/03/at-home/newsletter.html',
            uri: 'nyt://article/49f60863-8553-5a30-8888-6275273f3ed7',
            byline: '',
            item_type: 'Article',
            updated_date: '2021-12-03T16:30:06-05:00',
            created_date: '2021-12-03T16:30:06-05:00',
            published_date: '2021-12-03T16:30:06-05:00',
            material_type_facet: '',
            kicker: 'At Home and Away Newsletter',
            des_facet: ['Content Type: Service', 'internal-sub-only-nl'],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/multimedia/03At-Home-Newsletter/03At-Home-Newsletter-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1166,
                    width: 1750,
                    type: 'image',
                    subtype: 'photo',
                    caption: '',
                    copyright: 'Linda Merad',
                },
            ],
            short_url: 'https://nyti.ms/3DnHZm3',
        },
        {
            section: 'books',
            subsection: '',
            title: 'Almudena Grandes, Novelist of Spain’s Marginalized, Dies at 61',
            abstract:
                'Beginning with an acclaimed erotic novel, she became what the prime minister called “one of the most important writers of our time.”',
            url: 'https://www.nytimes.com/2021/12/03/books/almudena-grandes-dead.html',
            uri: 'nyt://article/942b3268-35f9-5c29-9694-fc6f78248e32',
            byline: 'By Raphael Minder',
            item_type: 'Article',
            updated_date: '2021-12-04T23:27:16-05:00',
            created_date: '2021-12-03T15:01:27-05:00',
            published_date: '2021-12-03T15:01:27-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Books and Literature',
                'Spanish Civil War (1936-39)',
                'Writing and Writers',
                'Deaths (Obituaries)',
                'Social Conditions and Trends',
                'The Ages of Lulu (Book)',
            ],
            org_facet: [],
            per_facet: ['Grandes, Almudena (1960-2021)'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/obituaries/05grandes-obit1/merlin_198453894_c3def995-a4b3-4b72-9e40-ec9ee6a04c2d-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1452,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Almudena Grandes in 2020. She had set about writing a six-novel series focused on Spain in the aftermath of its civil war in the 1930s. She completed five volumes.',
                    copyright: 'Pablo Martin/EPA, via Shutterstock',
                },
            ],
            short_url: 'https://nyti.ms/3GgcrQX',
        },
        {
            section: 'books',
            subsection: 'review',
            title: '‘You Are Here’: Mapping Climate Change, Make Believe and Murder',
            abstract:
                'New coffee table books offer an array of cartographical research for the most visual of learners.',
            url: 'https://www.nytimes.com/2021/12/03/books/review/murder-maps-usa-adam-selzer-atlas-of-imagined-places-matt-brown-rhys-b-davies-.html',
            uri: 'nyt://article/169ab261-124d-5981-ad20-844f4edf2cfb',
            byline: 'By Tina Jordan',
            item_type: 'Article',
            updated_date: '2021-12-03T16:53:21-05:00',
            created_date: '2021-12-03T14:53:42-05:00',
            published_date: '2021-12-03T14:53:42-05:00',
            material_type_facet: '',
            kicker: 'The Shortlist',
            des_facet: [
                'Books and Literature',
                'Murder Maps USA (Book)',
                'Atlas of Imagined Places (Book)',
                'Atlas of the Invisible (Book)',
                'Mapping Nature Across the Americas (Books)',
                'Detroit in 50 Maps (Book)',
            ],
            org_facet: [],
            per_facet: [
                'Hill, Alex B',
                'Uberti, Oliver',
                'Cheshire, James',
                'Selzer, Adam (1980- )',
                'Davies, Rhys B',
                'Brown, Matt (Author)',
                'Brosnan, Kathleen A',
                'Akerman, James R',
            ],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/05/books/review/05Shortlist-JORDAN/05Shortlist-JORDAN-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 512,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption: '',
                    copyright: 'John Gall',
                },
            ],
            short_url: 'https://nyti.ms/3G3rJbA',
        },
        {
            section: 'arts',
            subsection: 'television',
            title: 'The Best of Late Night This Week 🌙',
            abstract:
                "The late-night hosts spent most of the week talking about Omicron, the new Covid-19 variant. Here's what they had to say.",
            url: 'https://www.nytimes.com/interactive/2021/12/03/arts/television/best-of-late-night.html',
            uri: 'nyt://interactive/2b700a2e-7fe0-5cb9-a47b-8e6f04da9f4c',
            byline: 'By Trish Bendix',
            item_type: 'Interactive',
            updated_date: '2021-12-03T14:39:59-05:00',
            created_date: '2021-12-03T14:39:59-05:00',
            published_date: '2021-12-03T14:39:59-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Television'],
            org_facet: [],
            per_facet: ['Fallon, Jimmy'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/arts/03burst-boln-art2/03burst-boln-art2-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1152,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption: '',
                    copyright: 'Dado Ruvic/Reuters',
                },
            ],
            short_url: 'https://nyti.ms/3lxIKmy',
        },
        {
            section: 'style',
            subsection: '',
            title: 'Ansel Elgort and Offset Party During Art Basel',
            abstract:
                'Also, Gucci held a book signing for Mickalene Thomas and Jordan Barrett has a birthday dinner.',
            url: 'https://www.nytimes.com/2021/12/03/style/ansel-elgort-and-offset-party-during-art-basel.html',
            uri: 'nyt://article/00436602-2c34-50b3-9093-d02762753b4d',
            byline: 'By Diana Tsui',
            item_type: 'Article',
            updated_date: '2021-12-03T17:34:32-05:00',
            created_date: '2021-12-03T14:11:27-05:00',
            published_date: '2021-12-03T14:11:27-05:00',
            material_type_facet: '',
            kicker: 'The Social Ledger',
            des_facet: ['Art Basel Miami Beach', 'Parties (Social)', 'Fashion and Apparel'],
            org_facet: [],
            per_facet: ['Thomas, Mickalene'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/fashion/03social-ledger-flaunt2/merlin_198717090_800f906c-0930-49a8-8a2b-2e816cffa487-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Ansel Elgort, left, dances with Michele Lamy, center, at the Flaunt Magazine party during Art Basel. ',
                    copyright: 'Calla Kessler for The New York Times',
                },
            ],
            short_url: 'https://nyti.ms/3DfSJCU',
        },
        {
            section: 'movies',
            subsection: '',
            title: 'Kodi Smit-McPhee on Quiet Confidence, Chronic Pain and ‘The Power of the Dog’',
            abstract:
                'The 25-year-old Aussie delivers a scene-stealing performance as Peter, a bookish boy and aspiring doctor who’s more than he seems.',
            url: 'https://www.nytimes.com/2021/12/03/movies/kodi-smit-mcphee-power-of-the-dog.html',
            uri: 'nyt://article/6161de69-04a1-51bb-baa8-1209d9036c64',
            byline: 'By Sarah Bahr',
            item_type: 'Article',
            updated_date: '2021-12-04T09:39:45-05:00',
            created_date: '2021-12-03T14:04:18-05:00',
            published_date: '2021-12-03T14:04:18-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Actors and Actresses',
                'Content Type: Personal Profile',
                'Movies',
                'The Power of the Dog (Movie)',
            ],
            org_facet: [],
            per_facet: ['Smit-McPhee, Kodi', 'Campion, Jane'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/arts/03kodi-smit-mcphee-02/03kodi-smit-mcphee-02-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1366,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Kodi Smit-McPhee in “The Power of the Dog.” With his performance, “I was always thinking ‘This is too much,’” he said, but the director Jane Campion asked for more.',
                    copyright: 'Kirsty Griffin/Netflix',
                },
            ],
            short_url: 'https://nyti.ms/3GbqBmm',
        },
        {
            section: 'arts',
            subsection: 'music',
            title: '5 Minutes to Make You Love Classical Music',
            abstract:
                'What are the five minutes you’d play to make a friend fall in love with classical music? That’s what we’ve been asking artists and other notable people all year.',
            url: 'https://www.nytimes.com/interactive/2021/12/03/arts/music/five-minutes-classical.html',
            uri: 'nyt://interactive/5bf83494-11e8-5e02-83cb-3435ab79995b',
            byline: 'By Maya Salam',
            item_type: 'Interactive',
            updated_date: '2021-12-03T13:59:57-05:00',
            created_date: '2021-12-03T13:42:55-05:00',
            published_date: '2021-12-03T13:42:55-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Classical Music', 'Content Type: Service'],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/11/30/autossell/02fiveminutes-violin-gif-articleLarge-v2/02fiveminutes-violin-gif-articleLarge-v2-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 338,
                    width: 600,
                    type: 'image',
                    subtype: 'photo',
                    caption: '',
                    copyright: 'Angie Wang',
                },
            ],
            short_url: 'https://nyti.ms/3lxAhjg',
        },
        {
            section: 'movies',
            subsection: '',
            title: '‘The Power of the Dog’: About That Ending',
            abstract:
                'The movie’s subtle conclusion takes a moment to comprehend. But the director, Jane Campion, has a history of working in the realm of suggestion.',
            url: 'https://www.nytimes.com/2021/12/03/movies/the-power-of-the-dog-ending.html',
            uri: 'nyt://article/26bf226a-fa91-54f4-be27-8064daa4576c',
            byline: 'By Nicolas Rapold',
            item_type: 'Article',
            updated_date: '2021-12-04T09:42:56-05:00',
            created_date: '2021-12-03T12:39:35-05:00',
            published_date: '2021-12-03T12:39:35-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: ['Movies', 'The Power of the Dog (Movie)'],
            org_facet: [],
            per_facet: ['Campion, Jane'],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/02/arts/power-ending1/merlin_198348849_a5e8951f-7120-4bf0-98bb-b6c0b1e04876-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1140,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Benedict Cumberbatch, left, and Kodi Smit-McPhee in “The Power of the Dog.”',
                    copyright: 'Netflix',
                },
            ],
            short_url: 'https://nyti.ms/3lx4yP9',
        },
        {
            section: 'arts',
            subsection: 'music',
            title: 'Review: ‘Tosca’ Catches Fire at the Met Opera',
            abstract:
                'Sondra Radvanovsky and Brian Jagde sing thrillingly, and Yannick Nézet-Séguin conducts a superb performance of Puccini’s classic.',
            url: 'https://www.nytimes.com/2021/12/03/arts/music/met-opera-tosca.html',
            uri: 'nyt://article/9ae32637-7066-5064-bd1a-f0fc99d4b86b',
            byline: 'By Anthony Tommasini',
            item_type: 'Article',
            updated_date: '2021-12-03T17:16:23-05:00',
            created_date: '2021-12-03T12:34:04-05:00',
            published_date: '2021-12-03T12:34:04-05:00',
            material_type_facet: '',
            kicker: 'Critic’s Pick',
            des_facet: ['Opera', 'Tosca (Opera)'],
            org_facet: ['Metropolitan Opera'],
            per_facet: [
                'Gagnidze, George',
                'Jagde, Brian (Singer)',
                'Nezet-Seguin, Yannick',
                'Radvanovsky, Sondra',
                'Puccini, Giacomo',
            ],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/04/arts/03tosca/merlin_198673086_8f9c825b-d3a7-4f1b-9e98-6c7291e3abb3-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Sondra Radvanovsky and Brian Jagde star in a fiery revival of Puccini’s “Tosca” at the Metropolitan Opera.',
                    copyright: 'Ken Howard/Metropolitan Opera',
                },
            ],
            short_url: 'https://nyti.ms/3oibyRG',
        },
        {
            section: 'arts',
            subsection: '',
            title: 'The Best of 2021',
            abstract: '',
            url: 'https://www.nytimes.com/interactive/2021/arts/best-of-2021.html',
            uri: 'nyt://interactive/0783a083-ddef-50d6-9f90-3521e7277344',
            byline: '',
            item_type: 'Interactive',
            updated_date: '2021-12-03T12:05:10-05:00',
            created_date: '2021-12-03T12:05:10-05:00',
            published_date: '2021-12-03T12:05:10-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/01/arts/best-of-2021-cover/best-of-2021-cover-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption: '',
                    copyright:
                        'Clockwise from top left: Grant Spanier; Sara Krulwich/The New York Times; HBO; Sara Krulwich/The New York Times; Kirsty Griffin/Netflix',
                },
            ],
            short_url: 'https://nyti.ms/32MSCSC',
        },
        {
            section: 'arts',
            subsection: 'music',
            title: 'Mary J. Blige’s Daily Affirmation, and 12 More New Songs',
            abstract: 'Hear tracks by Grimes, Hurray for the Riff Raff, Kim Petras and others.',
            url: 'https://www.nytimes.com/2021/12/03/arts/music/playlist-mary-j-blige-grimes-cordae.html',
            uri: 'nyt://article/a74d5458-541f-58a7-98ab-69ea927aa101',
            byline: 'By Jon Pareles, Jon Caramanica, Isabelia Herrera and Giovanni Russonello',
            item_type: 'Article',
            updated_date: '2021-12-03T16:19:35-05:00',
            created_date: '2021-12-03T11:30:33-05:00',
            published_date: '2021-12-03T11:30:33-05:00',
            material_type_facet: '',
            kicker: 'The Playlist',
            des_facet: ['Pop and Rock Music', 'Folk Music', 'Rap and Hip-Hop', 'Jazz'],
            org_facet: ['Hurray for the Riff Raff (Music Group)', 'Inside Straight'],
            per_facet: [
                'Aurora (1996- )',
                'Blige, Mary J',
                'Grimes (1988- )',
                'Iduma, Emmanuel',
                'Kali Uchis (Singer)',
                'Lil Wayne',
                'McBride, Christian',
                'Petras, Kim (1992- )',
                'Segarra, Alynda',
                'Serpa, Sara',
                'Ozuna (Singer)',
                'Kerozen (Singer)',
                'Meah, Joe',
                'Carrion, Eladio',
                'Luar la L',
                'Ell, Lindsay',
            ],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/03/multimedia/03playlist/03playlist-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1365,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'Mary J. Blige’s “Good Morning Gorgeous” is one of the first singles from her Feb. 11 album of the same name.',
                    copyright: 'Andy Kropa/Invision, via Associated Press',
                },
            ],
            short_url: 'https://nyti.ms/3ot1Ax3',
        },
        {
            section: 'arts',
            subsection: 'design',
            title: 'Painter of Elijah Cummings Portrait Finds It’s a Career-Changer',
            abstract:
                'The Baltimore artist Jerrell Gibbs was commissioned to paint Maryland’s late Representative. The official portrait will be installed at the U.S. Capitol.',
            url: 'https://www.nytimes.com/2021/12/03/arts/design/jerrell-gibbs-elijah-cummings-portrait.html',
            uri: 'nyt://article/73afff40-57e7-549f-8101-f7e59754a25a',
            byline: 'By Hilarie M. Sheets',
            item_type: 'Article',
            updated_date: '2021-12-03T17:11:31-05:00',
            created_date: '2021-12-03T11:00:13-05:00',
            published_date: '2021-12-03T11:00:13-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Art',
                'Content Type: Personal Profile',
                'Capitol Building (Washington, DC)',
                'Museums',
                'Black People',
            ],
            org_facet: ['Baltimore Museum of Art'],
            per_facet: ['Gibbs, Jerrell', 'Cummings, Elijah E', 'Cummings, Maya Rockeymoore'],
            geo_facet: ['Baltimore (Md)'],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/04/arts/03cummings-portrait-1/merlin_198603993_c08ecf5f-1a29-462c-9034-0c5ab4fda2b3-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 1536,
                    width: 2048,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'The artist Jerrell Gibbs at his studio in Baltimore. The commission “gave me courage that people want to support what I bring to the table,” he said.',
                    copyright: 'Jared Soares for The New York Times',
                },
            ],
            short_url: 'https://nyti.ms/32KQOtl',
        },
        {
            section: 'movies',
            subsection: '',
            title: 'Five Action Movies to Stream Now',
            abstract:
                'Including bomb threats, bank robberies and more, the month’s action films pack a wallop.',
            url: 'https://www.nytimes.com/2021/12/03/movies/action-movies-streaming.html',
            uri: 'nyt://article/dee60d24-d670-5df8-bac9-ca5af719c383',
            byline: 'By Robert Daniels',
            item_type: 'Article',
            updated_date: '2021-12-04T00:00:14-05:00',
            created_date: '2021-12-03T11:00:06-05:00',
            published_date: '2021-12-03T11:00:06-05:00',
            material_type_facet: '',
            kicker: '',
            des_facet: [
                'Movies',
                'Dhamaka (Movie)',
                'The Gateway (Movie)',
                'Outlaws (Movie)',
                'Overrun (Movie)',
                'The Vault (Movie)',
            ],
            org_facet: [],
            per_facet: [],
            geo_facet: [],
            multimedia: [
                {
                    url: 'https://static01.nyt.com/images/2021/12/02/arts/streaming-action-vault/streaming-action-vault-superJumbo.jpg',
                    format: 'superJumbo',
                    height: 714,
                    width: 1000,
                    type: 'image',
                    subtype: 'photo',
                    caption:
                        'From left, Freddie Highmore, Sam Riley and Astrid Bergès-Frisbey in “The Vault.”',
                    copyright: 'Jorge Fuembuena',
                },
            ],
            short_url: 'https://nyti.ms/3Ga3PuR',
        },
    ],
};
